exports.createConfig = function createConfig() {
  return {
    extends: ['standard-with-typescript', 'wk', 'prettier'],
    rules: {},
    overrides: [
      {
        // typescripts
        files: ['*.ts', '*.tsx'],
        rules: {
          camelcase: 'off',
          'no-useless-constructor': 'off',
          'no-use-before-define': 'off',
          'no-unused-vars': 'off',
          'no-unused-expressions': 'off',
          'no-undef': 'off',
          'no-shadow': 'off',
          'no-empty-function': 'off',
          'lines-between-class-member': 'off',
          'dot-notation': 'off',
          'default-param-last': 'off',
          '@typescript-eslint/strict-boolean-expressions': 'off',
          '@typescript-eslint/restrict-template-expressions': 'off',
          '@typescript-eslint/restrict-plus-operands': 'warn',
          '@typescript-eslint/promise-function-async': 'off',
          '@typescript-eslint/prefer-readonly': 'off',
          '@typescript-eslint/prefer-optional-chain': 'warn',
          '@typescript-eslint/prefer-nullish-coalescing': 'warn',
          '@typescript-eslint/prefer-includes': 'warn',
          '@typescript-eslint/no-useless-constructor': ['error'],
          '@typescript-eslint/no-use-before-define': ['error'],
          '@typescript-eslint/no-unused-vars': 'warn',
          '@typescript-eslint/no-unused-expressions': 'warn',
          '@typescript-eslint/no-unnecessary-boolean-literal-compare': 'warn',
          '@typescript-eslint/no-shadow': 'error',
          '@typescript-eslint/no-non-null-assertion': 'warn',
          '@typescript-eslint/no-floating-promises': 'off',
          '@typescript-eslint/no-empty-interface': 'warn',
          '@typescript-eslint/no-empty-function': 'warn',
          '@typescript-eslint/naming-convention': 'warn',
          '@typescript-eslint/method-signature-style': 'off',
          '@typescript-eslint/lines-between-class-members': 'off',
          '@typescript-eslint/explicit-function-return-type': 'off',
          '@typescript-eslint/dot-notation': 'warn',
          '@typescript-eslint/default-param-last': ['warn'],
          '@typescript-eslint/consistent-type-definitions': 'warn',
          '@typescript-eslint/array-type': 'warn',
        },
        parser: '@typescript-eslint/parser',
        parserOptions: {
          warnOnUnsupportedTypeScriptVersion: true,
          ecmaVersion: 'es11',
          lib: ['esNext'],
          project: './tsconfig.json',
        },
      },
    ],
  };
};
